name: R-CMD-check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_LIBS_USER: ~/R/library

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            ggplot2
            dplyr
            tidyr
            readr
            broom
            testthat
          extra-packages: |
            covr
            lintr

      - name: Run R CMD check
        run: | 
          Rscript -e "install.packages('remotes', repos = 'https://cloud.r-project.org')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
          Rscript -e "testthat::test_dir('tests')"
          Rscript -e "covr::report()"
          Rscript -e "lintr::lint_package()"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: galafis/Biostatistics-Research-Platform-R

